package x

const (
	JsFnAddListener              = "addListener"
	JsFnCaptureVisibleTab        = "captureVisibleTab"
	JsFnConnect                  = "connect"
	JsFnConnectNative            = "connectNative"
	JsFnCreate                   = "create"
	JsFnDetectLanguage           = "detectLanguage"
	JsFnDiscard                  = "discard"
	JsFnDuplicate                = "duplicate"
	JsFnExecuteScript            = "executeScript"
	JsFnGet                      = "get"
	JsFnGetAllInWindow           = "getAllInWindow"
	JsFnGetBackgroundPage        = "getBackgroundPage"
	JsFnGetCurrent               = "getCurrent"
	JsFnGetManifest              = "getManifest"
	JsFnGetPackageDirectoryEntry = "getPackageDirectoryEntry"
	JsFnGetPlatformInfo          = "getPlatformInfo"
	JsFnGetSelected              = "getSelected"
	JsFnGetURL                   = "getURL"
	JsFnGetZoom                  = "getZoom"
	JsFnGetZoomSettings          = "getZoomSettings"
	JsFnGoBack                   = "goBack"
	JsFnGoForward                = "goForward"
	JsFnGroup                    = "group"
	JsFnHighlight                = "highlight"
	JsFnInsertCSS                = "insertCSS"
	JsFnMove                     = "move"
	JsFnOpenOptionsPage          = "openOptionsPage"
	JsFnQuery                    = "query"
	JsFnReload                   = "reload"
	JsFnRemove                   = "remove"
	JsFnRemoveCSS                = "removeCSS"
	JsFnRemoveListener           = "removeListener"
	JsFnRequestUpdateCheck       = "requestUpdateCheck"
	JsFnRestart                  = "restart"
	JsFnRestartAfterDelay        = "restartAfterDelay"
	JsFnSendMessage              = "sendMessage"
	JsFnSendNativeMsg            = "sendNativeMessage"
	JsFnSendRequest              = "sendRequest"
	JsFnSetUninstallURL          = "setUninstallURL"
	JsFnSetZoom                  = "setZoom"
	JsFnSetZoomSettings          = "setZoomSettings"
	JsFnUngroup                  = "ungroup"
	JsFnUpdate                   = "update"
)
