package x

const (
	JsKeyActive               = "active"
	JsKeyAudible              = "audible"
	JsKeyAutoDiscardable      = "autoDiscardable"
	JsKeyDiscarded            = "discarded"
	JsKeyFavIconURL           = "favIconUrl"
	JsKeyGroupID              = "groupId"
	JsKeyHeight               = "height"
	JsKeyHighlighted          = "highlighted"
	JsKeyID                   = "id"
	JsKeyIndex                = "index"
	JsKeyLastError            = "lastError"
	JsKeyMutedInfo            = "mutedInfo"
	JsKeyOnBrowserUpdateAvail = "onBrowserUpdateAvailable"
	JsKeyOnConnect            = "onConnect"
	JsKeyOnConnectExternal    = "onConnectExternal"
	JsKeyOnConnectNative      = "onConnectNative"
	JsKeyOnInstalled          = "onInstalled"
	JsKeyOnMessage            = "onMessage"
	JsKeyOnMessageExternal    = "onMessageExternal"
	JsKeyOnRestartRequired    = "onRestartRequired"
	JsKeyOnStartup            = "onStartup"
	JsKeyOnSuspend            = "onSuspend"
	JsKeyOnSuspendCanceled    = "onSuspendCanceled"
	JsKeyOnUpdateAvailable    = "onUpdateAvailable"
	JsKeyOpenerTabID          = "openerTabId"
	JsKeyPendingURL           = "pendingUrl"
	JsKeyPinned               = "pinned"
	JsKeySelected             = "selected"
	JsKeySessionID            = "sessionID"
	JsKeyStatus               = "status"
	JsKeyTitle                = "title"
	JsKeyURL                  = "url"
	JsKeyVersion              = "version"
	JsKeyWidth                = "width"
	JsKeyWindowID             = "windowId"
	JsKeyExtensionID          = "extensionId"
	JsKeyMuted                = "muted"
	JsKeyReason               = "reason"
	JsKeyIsFile               = "isFile"
	JsKeyName                 = "name"
	JsKeyFullPath             = "fullPath"
	JsKeyFilesystem           = "filesystem"
)
